version: '3'

services:
  debug:
    image: debug
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - ${SRC:-./src}:/usr/src/app/
    ports:
      - 8000:8000
      - 5858:5858
    command: nodemon -L --inspect=0.0.0.0:5858 app.js
