version: '3'

services:
  debug:
    image: debug
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - ${SRC:-./src}:/usr/src/app/
    ports:
      - 8000:8000
      - 9229:9229
    command: nodemon -L --inspect-brk=0.0.0.0:9229 app.js
